services:

  redis:
    image: redis:latest
    container_name: chat-redis
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka:latest
    container_name: chat-kafka
    ports:
      - "9092:9092"